import { Platform, Task, HubSection, Campaign, Partner } from './types';

export const platforms: Platform[] = [
  {
    id: '1',
    name: 'Amazon Europe',
    type: 'Wholesale Marketplace',
    market: 'EU',
    website: 'amazon.co.uk',
    owner: 'Sarah Chen',
    priority: 'High',
    estimatedValue: 120000,
    fitScore: 9,
    riskLevel: 'Medium',
    currentStage: 'Live',
    dateStarted: '2023-11-01',
    lastUpdate: '2024-03-20',
    productsUploaded: true,
    salesStarted: true,
    firstOrderDate: '2023-12-15',
    nextStep: 'Scale advertising budget',
    dueDate: '2024-04-01',
    contactPerson: 'Marcus Webb',
    email: 'm.webb@amazon.com',
    requirements: ['VAT ID', 'Brand Registry'],
  },
  {
    id: '2',
    name: 'Faire Wholesale',
    type: 'Wholesale',
    market: 'US / CA',
    website: 'faire.com',
    owner: 'Alex Rivera',
    priority: 'High',
    estimatedValue: 85000,
    fitScore: 10,
    riskLevel: 'Low',
    currentStage: 'Approved',
    dateStarted: '2024-01-15',
    lastUpdate: '2024-03-24',
    productsUploaded: false,
    salesStarted: false,
    nextStep: 'Finalize product catalog upload',
    dueDate: '2024-03-30',
    contactPerson: 'Jenna Lyons',
    email: 'jenna@faire.com',
    requirements: ['Wholesale pricing sheet', 'Product imagery'],
  },
  {
    id: '3',
    name: 'Wayfair US',
    type: 'Dropshipping',
    market: 'US',
    website: 'wayfair.com',
    owner: 'Sarah Chen',
    priority: 'Medium',
    estimatedValue: 50000,
    fitScore: 8,
    riskLevel: 'High',
    currentStage: 'In Review',
    dateStarted: '2024-02-10',
    lastUpdate: '2024-03-22',
    productsUploaded: false,
    salesStarted: false,
    nextStep: 'Follow up on compliance docs',
    dueDate: '2024-03-25',
    blockers: 'Awaiting insurance certificate verification',
    contactPerson: 'Robert Hall',
  },
  {
    id: '4',
    name: 'BestBuy Canada',
    type: 'Retail Marketplace',
    market: 'CA',
    website: 'bestbuy.ca',
    owner: 'Alex Rivera',
    priority: 'Low',
    estimatedValue: 30000,
    fitScore: 6,
    riskLevel: 'Medium',
    currentStage: 'Research',
    dateStarted: '2024-03-01',
    lastUpdate: '2024-03-15',
    productsUploaded: false,
    salesStarted: false,
    nextStep: 'Analyze competitor pricing on platform',
    dueDate: '2024-04-10',
  },
  {
    id: '5',
    name: 'Saks Fifth Avenue',
    type: 'Strategic Partnership',
    market: 'Global',
    website: 'saks.com',
    owner: 'James Sterling',
    priority: 'High',
    estimatedValue: 250000,
    fitScore: 9,
    riskLevel: 'Medium',
    currentStage: 'Applied',
    dateStarted: '2024-03-10',
    lastUpdate: '2024-03-25',
    productsUploaded: false,
    salesStarted: false,
    nextStep: 'Submit partnership proposal deck',
    dueDate: '2024-03-28',
    contactPerson: 'Eleanor Vance',
  }
];

export const tasks: Task[] = [
  {
    id: 't1',
    title: 'Update VAT documents',
    linkedPlatformId: '1',
    linkedPlatformName: 'Amazon Europe',
    owner: 'Sarah Chen',
    priority: 'High',
    dueDate: '2024-03-28',
    status: 'In Progress',
  },
  {
    id: 't2',
    title: 'Review insurance policy',
    linkedPlatformId: '3',
    linkedPlatformName: 'Wayfair US',
    owner: 'Sarah Chen',
    priority: 'High',
    dueDate: '2024-03-24',
    status: 'Overdue',
  },
  {
    id: 't3',
    title: 'Draft Faire pitch email',
    linkedPlatformId: '2',
    linkedPlatformName: 'Faire Wholesale',
    owner: 'Alex Rivera',
    priority: 'Medium',
    dueDate: '2024-03-26',
    status: 'Open',
  },
  {
    id: 't4',
    title: 'Prepare Saks proposal deck',
    linkedPlatformId: '5',
    linkedPlatformName: 'Saks Fifth Avenue',
    owner: 'James Sterling',
    priority: 'High',
    dueDate: '2024-03-28',
    status: 'In Progress',
  },
  {
    id: 't5',
    title: 'Initial catalog audit',
    linkedPlatformId: '2',
    linkedPlatformName: 'Faire Wholesale',
    owner: 'Alex Rivera',
    priority: 'Low',
    dueDate: '2024-03-20',
    status: 'Completed',
  },
  {
    id: 't6',
    title: 'Verify EIN validation',
    linkedPlatformId: '1',
    linkedPlatformName: 'Amazon Europe',
    owner: 'Sarah Chen',
    priority: 'Medium',
    dueDate: '2024-03-15',
    status: 'Completed',
  }
];

export const hubSections: HubSection[] = [
  {
    id: 'h1',
    title: 'Brand Mission & Vision',
    category: 'Brand',
    content: 'We empower modern living through sustainable, high-performance modular furniture systems. Our vision is to be the foundation of flexible workspaces worldwide.',
    lastUpdated: '2024-01-10',
  },
  {
    id: 'h2',
    title: 'Standard Application FAQ',
    category: 'FAQs',
    content: 'Q: Do you offer drop-shipping? A: Yes, within 48h fulfillment windows. Q: Where is your warehouse? A: Dayton, OH and Rotterdam, NL.',
    lastUpdated: '2024-02-15',
  },
  {
    id: 'h3',
    title: 'W9 - US Operations',
    category: 'Legal',
    content: 'Last uploaded 2024-01-01. Version 2.4. Includes updated EIN.',
    lastUpdated: '2024-01-01',
  }
];

export const campaigns: Campaign[] = [
  {
    id: 'c1',
    name: 'Spring Renewal Promo',
    type: 'Promotion',
    status: 'Active',
    budget: 25000,
    spend: 12400,
    reach: 450000,
    conversions: 890,
    owner: 'Sarah Chen',
    startDate: '2024-03-01',
    endDate: '2024-04-15',
  },
  {
    id: 'c2',
    name: 'Meta Awareness Wave',
    type: 'Paid Ads',
    status: 'Active',
    budget: 50000,
    spend: 21000,
    reach: 1200000,
    conversions: 450,
    owner: 'James Sterling',
    startDate: '2024-03-10',
    endDate: '2024-05-10',
  },
  {
    id: 'c3',
    name: 'Micro-Influencer Pilot',
    type: 'Creator Outreach',
    status: 'Scheduled',
    budget: 15000,
    spend: 0,
    reach: 0,
    conversions: 0,
    owner: 'Alex Rivera',
    startDate: '2024-04-01',
    endDate: '2024-06-01',
  }
];

export const partnerships: Partner[] = [
  {
    id: 'p1',
    name: 'Parenting Bloom Blog',
    type: 'Influencer',
    status: 'Active',
    contact: 'Mary Poppins',
    impactScore: 9,
    owner: 'Alex Rivera',
    lastContact: '2024-03-20',
    notes: 'High conversion on family-oriented modular units.',
  },
  {
    id: 'p2',
    name: 'Global Milk Co.',
    type: 'B2B Partner',
    status: 'Negotiating',
    contact: 'John Cow',
    impactScore: 7,
    owner: 'James Sterling',
    lastContact: '2024-03-22',
    notes: 'Co-branding opportunity for kitchen efficiency sets.',
  },
  {
    id: 'p3',
    name: 'Reddit Home Office Community',
    type: 'Community',
    status: 'Prospecting',
    contact: 'u/Moderator',
    impactScore: 10,
    owner: 'Sarah Chen',
    lastContact: '2024-03-15',
    notes: 'Direct outreach for AMA session.',
  }
];
